language: python
services:
  - docker
  - mongodb

before_script:
  - sleep 15

before_install:
  - docker build --build-arg ENV=travisci -t laravel_migration .

script: docker run --network host --env MONGODB_URI=mongodb://127.0.0.1:27017 --env MONGO_DB=teste laravel_migration:latest python -m pytest

before_deploy:
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}

#deploy:
#  provider: releases
#  token: $GITHUB_OAUTH_TOKEN
#  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
#  draft: true
#  on:
#    tags: true