language: python
services:
  - docker
  - mongodb

before_script:
  - sleep 15

before_install:
  - docker build --build-arg ENV=travisci -t laravel_migration .
  - cp .env.example .env

jobs:
  include:
    - stage: "Migration"
      name: "Generate Migration File And Run"
      script:
        - ./migrator make:migration --build migration_travis_test
        - ./migrator migrate --build
        - ./migrator migrate:rollback --build
    - stage: "Seed"
      name: "Generate Seeds File And Run"
      script:
        - ./migrator make:seed --build seed_travis_ci
        - ./migrator run:seed --build
    #script: docker run --network bubble --env MONGODB_URI=mongodb://db.flags:27017 --env MONGO_DB=teste laravel_migration:latest python -m pytest tests