#!/bin/bash

set -e

cd `dirname $0`

PWD=$(pwd)

##SET FOLDERS
MIGRATIONS_FOLDER=${PWD}/migrations #Mude caso deseje utilizar outra pasta
DOCKER_FILE=${PWD}
ENV_FILE=${PWD}/.env

##SET COLORS
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
NC="\033[0m" # NoColor

######################
## DockerCompose Up ##
######################
generate() {
    args=$(tr ' ' '\n' <<< "$@" | grep -v '^+' | tr '\n' ' ')

    #Check If Arg has treatment
    for arg in $args
     do
      case $arg in
        '-h')
            helperMessageGenerate
            exit 1;
            ;;
        '--build')
            docker build ${DOCKER_FILE} --tag laravel_migration
            ;;
           *) ;;
      esac
    done

    [ ! -z $(docker images -q  laravel_migration:latest) ] || docker build ${DOCKER_FILE} --tag laravel_migration

    docker run \
      --volume ${MIGRATIONS_FOLDER}:/app/migrations \
      --env-file ${ENV_FILE} \
      laravel_migration:latest \
      python generator.py ${arg}
}

######################
## DockerCompose Up ##
######################
migrate() {
    args=$(tr ' ' '\n' <<< "$@" | grep -v '^+' | tr '\n' ' ')

    #Check If Arg has treatment
    for arg in $args
     do
      case $arg in
        '-h')
            helperMessageMigrate
            exit 1;
            ;;
        '--build')
            docker build ${DOCKER_FILE} --tag laravel_migration
            ;;
           *) ;;
      esac
    done

    [ ! -z $(docker images -q  laravel_migration:latest) ] || docker build ${DOCKER_FILE} --tag laravel_migration

    docker run \
      --volume ${MIGRATIONS_FOLDER}:/app/migrations \
      --env-file ${ENV_FILE} \
      laravel_migration:latest \
      python migrator_function.py migrate
}

########################
## DockerCompose Down ##
########################
rollback() {
    args=$(tr ' ' '\n' <<< "$@" | grep -v '^+' | tr '\n' ' ')

    #Check If Arg has treatment
    for arg in $args
     do
      case $arg in
        '-h')
            helperMessageRollback
            exit 1;
            ;;
        '--build')
            docker build ${DOCKER_FILE} --tag laravel_migration
            ;;
           *) ;;
      esac
    done

    [ ! -z $(docker images -q  laravel_migration:latest) ] || docker build ${DOCKER_FILE} --tag laravel_migration

    docker run \
      --volume ${MIGRATIONS_FOLDER}:/app/migrations \
      --env-file ${ENV_FILE} \
      laravel_migration:latest \
      python migrator_function.py rollback
}

#########################
## Show Message Helper ##
#########################
helperMessage() {
    echo -e "${GREEN} ## MongoDB Migration ${NC} Version 1.0.0 \n"
    echo -e "${YELLOW} Usage: "
    echo -e "${NC}   command [options] \n"
    echo -e "${YELLOW} Available Commands: "
    echo -e "${GREEN}   generate       ${NC} Generate a Migration File and Save in Migrations folder"
    echo -e "${GREEN}   migrate        ${NC} Run All Migrations"
    echo -e "${GREEN}   rollback       ${NC} Rollback Migration"
}

####################################
## Show Message Helper Up Command ##
####################################
helperMessageGenerate() {
    echo -e "${YELLOW} Description: "
    echo -e "${NC}     Generate a Migration File and save in migrations folder \n"

    echo -e "${YELLOW} Usage: "
    echo -e "${NC}        generate [options] MIGRATION_NAME \n"

    echo -e "${YELLOW} Options: "
    echo -e "${GREEN}   -h                    ${NC} Ask For Support"
    echo -e "${GREEN}   --build               ${NC} Force Image Build before starting containers."
}

######################################
## Show Message Helper Logs Command ##
######################################
helperMessageMigrate() {
    echo -e "${YELLOW} Description: "
    echo -e "${NC}     Run All Pending Migrations \n"

    echo -e "${YELLOW} Usage: "
    echo -e "${NC}        migrate [options] \n"

    echo -e "${YELLOW} Options: "
    echo -e "${GREEN}   -h                    ${NC} Ask For Support"
    echo -e "${GREEN}   --build               ${NC} Force Image Build before starting containers."
}

######################################
## Show Message Helper Exec Command ##
######################################
helperMessageRollback() {
    echo -e "${YELLOW} Description: "
    echo -e "${NC}     Rollback last Migration executed\n"

    echo -e "${YELLOW} Usage: "
    echo -e "${NC}        rollback [options] \n"

    echo -e "${YELLOW} Options: "
    echo -e "${GREEN}   -h                    ${NC} Ask For Support"
    echo -e "${GREEN}   --build               ${NC} Force Image Build before starting containers."
}

######################################
## Function From->To call Functions ##
######################################
aliases() {
    params="$*"
    if [ -z "$1" ]
    then
        helperMessage
    fi

    arg="$1"; shift

    case "$arg" in
        "migrate" )
            migrate "$@";;
        "rollback" )
            rollback "$@";;
        "generate" )
            generate "$@";;
        *)
            helperMessage;;
    esac
}

###########
## Start ##
###########
aliases "$@"
